use tonic::{Request, Response, Status};
use std::path::PathBuf;
use glob::glob;
use std::fs;


/// Use the generated proto types (module generated by tonic_build via `tonic::include_proto!("find_table")` in lib.rs)
use crate::find_table::table_lookup_server::TableLookup;
use crate::find_table::{FindTableRequest, FindTableResponse};

#[derive(Clone)]
pub struct TableLookupService {
    pub base_dir: PathBuf,
}

impl TableLookupService {
    pub fn new(base_dir: PathBuf) -> Self {
        Self { base_dir }
    }
}

#[tonic::async_trait]
impl TableLookup for TableLookupService {
    async fn find_table(
        &self,
        req: Request<FindTableRequest>,
    ) -> Result<Response<FindTableResponse>, Status> {
        let r = req.into_inner();
        let table_name = r.table_name;
        let column_name = r.column_name;

        // pattern: {base_dir}/owner_*/<table_name>$
        let pattern = format!("{}/owner_*/{}", self.base_dir.display(), table_name);

        for entry in glob(&pattern).map_err(|e| Status::internal(format!("glob error: {}", e)))? {
            let table_dir = match entry {
                Ok(p) => p,
                Err(_) => continue,
            };

            let schema_path = table_dir.join("schema.json");
            if !schema_path.exists() {
                continue;
            }
            let data = fs::read_to_string(&schema_path)
                .map_err(|e| Status::internal(format!("read schema.json error: {}", e)))?;

            let parsed: serde_json::Value = serde_json::from_str(&data)
                .map_err(|e| Status::internal(format!("parse schema.json error: {}", e)))?;

            let has_column = parsed.get("columns")
                .and_then(|v| v.as_array())
                .map(|cols| {
                    cols.iter().any(|c| {
                        c.get("name")
                            .and_then(|n| n.as_str())
                            .map(|s| s == column_name)
                            .unwrap_or(false)
                    })
                })
                .unwrap_or(false);

            if !has_column {
                continue;
            }

            let row_count = parsed.get("row_count").and_then(|v| v.as_u64()).unwrap_or(0);

            let resp = FindTableResponse {
                found: true,
                table_dir: table_dir.to_string_lossy().into_owned(),
                row_count,
                schema_json: data,
            };
            info!("Table '{}' with column '{}' found at '{}'", table_name, column_name, table_dir.display());

            return Ok(Response::new(resp));
        }

        Ok(Response::new(FindTableResponse { found: false, table_dir: "".into(), row_count: 0, schema_json: "".into() }))
    }
}
